`FeatureFormView` - Attachment handling revisions
Esri/arcgis-maps-sdk-swift-toolkit pull request #729
Opened 2024-05-16 02:03 UTC by dfeinzimer

Related Apollo 684

2024-05-31 00:44 UTC, dfeinzimer commented
This is ready for review once again

2024-05-31 20:03 UTC, dfeinzimer commented
Still ready for review. Updated `AttachmentFormElement.deleteAttachment(attachment)` to `AttachmentFormElement.delete(attachment)`.

2024-05-31 20:45 UTC, mhdostal commented
> Updated `AttachmentFormElement.deleteAttachment(attachment)` to `AttachmentFormElement.delete(attachment)`.

Is that what the new generated code outputs?

2024-05-31 20:56 UTC, mhdostal commented
Does the `AttachmentImportMenu.init(element: AttachmentsFormElement, onAdd: ((FeatureAttachment) async throws -> Void)? = nil)` method still need the `onAdd` argument to be `async throws`?

Same question for `onDelete` and `onRename` for the `AttachmentPreview` class?

2024-05-31 20:57 UTC, mhdostal requested changes

2024-05-31 20:57 UTC, mhdostal commented on Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift
>      func onRename(attachmentModel: AttachmentModel, newAttachmentName: String) async throws -> Void {
This no longer needs to be `async throws`.
```suggestion
    func onRename(attachmentModel: AttachmentModel, newAttachmentName: String) -> Void {
```

2024-05-31 20:57 UTC, mhdostal commented on Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift
>      func onDelete(attachmentModel: AttachmentModel) async throws -> Void {
This no longer needs to be `async throws`.
```suggestion
    func onDelete(attachmentModel: AttachmentModel) -> Void {
```

2024-05-31 22:59 UTC, dfeinzimer commented
> Is that what the new generated code outputs?

It looks like taking the `attachments` property out of generation to make it not-cached actually caused that.. which I wouldn't have expected. Reverting for now.

2024-06-02 15:24 UTC, mhdostal commented
I think `AttachmentFormElement.delete(attachment)` is actually better. See the Swift API doc [here](https://www.swift.org/documentation/api-design-guidelines/#naming).

2024-06-02 15:26 UTC, mhdostal approved these changes
This looks good. We can figure out the naming during the API Audit.

2024-06-03 17:27 UTC, merged