Fix`AttachmentCameraControllerTests.testOnCameraCaptureModeChanged()`
Esri/arcgis-maps-sdk-swift-toolkit pull request #821
Opened 2024-07-18 21:49 UTC by dfeinzimer

Followup to #811

2024-07-18 21:56 UTC, njarecha requested changes
Few suggestions

2024-07-18 21:56 UTC, njarecha commented on Test Runner/UI Tests/AttachmentCameraControllerTests.swift
> +        let springboard = XCUIApplication(bundleIdentifier: .springboardIdentifier)
Since, it is used only on 1 place.
```suggestion
        let springboard = XCUIApplication(bundleIdentifier: "com.apple.springboard")
```

2024-07-18 21:56 UTC, njarecha commented on Test Runner/UI Tests/AttachmentCameraControllerTests.swift
> +}
```suggestion
```

2024-07-18 21:56 UTC, njarecha commented on Test Runner/UI Tests/AttachmentCameraControllerTests.swift
> +        allowButton.tap()
```suggestion
        // Wait for camera access alert's allow button.
        XCTAssertTrue(allowButton.waitForExistence(timeout: 5))
        allowButton.tap()
```

2024-07-18 21:56 UTC, njarecha commented on Test Runner/UI Tests/AttachmentCameraControllerTests.swift
> +        allowButton.tap()
```suggestion
        // Wait for microphone access alert's allow button.
        XCTAssertTrue(allowButton.waitForExistence(timeout: 5))
        allowButton.tap()
```

2024-07-18 21:58 UTC, dfeinzimer commented
Thank you @njarecha!

2024-07-18 22:10 UTC, njarecha approved these changes

2024-07-19 14:47 UTC, mhdostal approved these changes

2024-07-19 16:47 UTC, merged